local application = require("test.application")

function TestEmployeeFound()
    local app = application()

    describe("Company Directory Employee Found Scenario", function()
        it("Answer the phone, and greet the caller", function()
            app.should.channel.answer()
            app.should.channel.say("Thanks for calling ACME Manufacturing! Welcome to our company directory.")
        end)
        it("Ask for the first three letters, using channel.gather", function()
            app.should.channel.gather("252")
        end)
        it("Asks to dial the first entry found", function()
            app.should.channel.gather("1")
        end)
        it("Should announce the dialing", function()
            app.should.channel.say("Dialing Lionel Blake")
        end)
        it("Should dial the employee's phone #", function()
            app.should.channel.dial("13175551212")
        end)
    end)
end

function TestEmployeeNotFound()
    local app = application()

    describe("Company Directory Employee Not Found", function()
        it("Answer the phone, and greet the caller", function()
            app.should.channel.answer()
            app.should.channel.say("Thanks for calling ACME Manufacturing! Welcome to our company directory.")
        end)
        it("Ask for the first three letters, using channel.gather", function()
            app.should.channel.gather("999")
        end)
        it("Lets the caller know that an employee wasnt found", function()
            app.should.channel.say("There were no employees found with that last name. Sorry!")
        end)
    end)
end

function TestEmployeeNotFoundThenFound()
    local app = application()

    describe("Company Directory Employee Not Found, then found", function()
        it("Answer the phone, and greet the caller", function()
            app.should.channel.answer()
            app.should.channel.say("Thanks for calling ACME Manufacturing! Welcome to our company directory.")
        end)
        it("Ask for the first three letters, using channel.gather", function()
            app.should.channel.gather("999")
        end)
        it("Lets the caller know that an employee wasnt found", function()
            app.should.channel.say("There were no employees found with that last name. Sorry!")
        end)
        it("Ask for the first three letters, using channel.gather", function()
            app.should.channel.gather("252")
        end)
        it("Asks to dial the first entry found", function()
            app.should.channel.gather("1")
        end)
    end)
end


TestEmployeeNotFound()
TestEmployeeNotFoundThenFound()
TestEmployeeFound()
